"""
FAISS vector store manager.

Responsibilities:
  - Build embeddings (OpenAI by default, sentence-transformers as fallback).
  - Persist / load a FAISS index on disk so we don't re-embed on every start.
  - Provide thread-safe access for the FastAPI service.

The index is stored on disk at ``settings.vectorstore_dir`` as two files:
``index.faiss`` and ``index.pkl`` (LangChain's standard format).
"""
from __future__ import annotations

import threading
from pathlib import Path
from typing import Iterable

from langchain_community.vectorstores import FAISS
from langchain_core.documents import Document
from langchain_core.embeddings import Embeddings
from loguru import logger

from backend.core.config import settings


# ─── Embedding factory ────────────────────────────────────────────────────


def get_embeddings() -> Embeddings:
    """Return the configured embedding backend.

    Defaults to OpenAI embeddings; falls back to a local sentence-transformers
    model when ``USE_LOCAL_EMBEDDINGS=true`` or no OpenAI key is set. The local
    path is useful for offline dev and integration tests.
    """
    if settings.use_local_embeddings or not settings.openai_api_key:
        from langchain_community.embeddings import HuggingFaceEmbeddings

        logger.info(f"Using local embeddings: {settings.local_embedding_model}")
        return HuggingFaceEmbeddings(
            model_name=settings.local_embedding_model,
            encode_kwargs={"normalize_embeddings": True},
        )

    from langchain_openai import OpenAIEmbeddings

    logger.info(f"Using OpenAI embeddings: {settings.openai_embedding_model}")
    return OpenAIEmbeddings(
        model=settings.openai_embedding_model,
        api_key=settings.openai_api_key,
    )


# ─── Manager ──────────────────────────────────────────────────────────────


class VectorStoreManager:
    """Singleton-ish wrapper around a FAISS index with disk persistence."""

    _instance: "VectorStoreManager | None" = None
    _lock = threading.Lock()

    def __new__(cls) -> "VectorStoreManager":
        with cls._lock:
            if cls._instance is None:
                cls._instance = super().__new__(cls)
                cls._instance._store = None  # type: ignore[attr-defined]
                cls._instance._embeddings = None  # type: ignore[attr-defined]
            return cls._instance

    # ─── Lifecycle ────────────────────────────────────────────────────────

    @property
    def path(self) -> Path:
        return Path(settings.vectorstore_dir)

    @property
    def embeddings(self) -> Embeddings:
        if self._embeddings is None:  # type: ignore[has-type]
            self._embeddings = get_embeddings()
        return self._embeddings  # type: ignore[return-value]

    @property
    def store(self) -> FAISS | None:
        return self._store  # type: ignore[return-value]

    def load_or_init(self) -> FAISS:
        """Load the persisted index if it exists, otherwise create an empty one.

        FAISS requires at least one document to construct a store, so the
        "empty" path inserts a sentinel document and immediately removes it.
        """
        if self._store is not None:  # type: ignore[has-type]
            return self._store  # type: ignore[return-value]

        if (self.path / "index.faiss").exists():
            logger.info(f"Loading FAISS index from {self.path}")
            # allow_dangerous_deserialization is required for FAISS.load_local in
            # recent langchain-community releases; the index file is generated by us.
            self._store = FAISS.load_local(
                str(self.path),
                self.embeddings,
                allow_dangerous_deserialization=True,
            )
        else:
            logger.info(f"No index found at {self.path}; initializing empty FAISS store")
            sentinel = Document(page_content="__init__", metadata={"source": "__sentinel__"})
            self._store = FAISS.from_documents([sentinel], self.embeddings)
            # Drop the sentinel so retrieval doesn't return it.
            self._store.delete([next(iter(self._store.docstore._dict.keys()))])
        return self._store  # type: ignore[return-value]

    def save(self) -> None:
        if self._store is None:  # type: ignore[has-type]
            return
        self.path.mkdir(parents=True, exist_ok=True)
        self._store.save_local(str(self.path))
        logger.info(f"FAISS index saved to {self.path} (size={self.size()})")

    # ─── Mutation ─────────────────────────────────────────────────────────

    def add_documents(self, docs: Iterable[Document]) -> int:
        """Add documents to the index. Returns the number added."""
        store = self.load_or_init()
        docs = list(docs)
        if not docs:
            return 0
        store.add_documents(docs)
        self.save()
        return len(docs)

    def size(self) -> int:
        """Number of vectors currently in the index."""
        if self._store is None:  # type: ignore[has-type]
            return 0
        return self._store.index.ntotal

    def reset(self) -> None:
        """Drop the in-memory and on-disk index. Useful for tests."""
        import shutil

        self._store = None  # type: ignore[assignment]
        if self.path.exists():
            shutil.rmtree(self.path)
        logger.warning(f"Vector store reset at {self.path}")
